---
<% if ENV['use_docker'] == 'true' %>
driver:
  name: docker
  binary: /usr/bin/docker
  socket: unix:///var/run/docker.sock
  use_sudo: false
  provision_command: curl -L http://www.chef.io/chef/install.sh | bash
<% else %>
driver:
  name: vagrant
  provision_command: curl -L http://www.chef.io/chef/install.sh | bash
<% end %>
provisioner:
  name: chef_zero
  cookbooks_path:
      - ../cookbooks
      - ../site-cookbooks
  data_bag_path: "data_bags"
  environment_path: "environments"
  nodes_path: "nodes"
  roles_path: "roles"
  encrypted_data_bag_secret_key_path: "/etc/chef/encrypted_data_bag_secret"
  solo_rb:
    ssl_verify_mode: verify_peer
  client_rb:
    environment: local

platforms:
  - name: centos-7.1
    driver_config:
      box: opscode-centos-7.1
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box

suites:
  - name: kitchen-demo-app-server
    run_list:
      - role[app-tomcat]
  - name: kitchen-demo-db-server
    run_list:
      - role[db-mysql]
  - name: kitchen-demo-lb-server
    run_list:
      - role[lb-haproxy]