source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef'
gem 'chef-provisioning-aws'
gem 'chef-provisioning-docker', '~> 0.9.0'
gem 'chefspec'
gem 'docker'
gem 'docker-api', '~> 1.26', '>= 1.26.2'
gem 'kitchen-docker'
gem 'kitchen-ec2'
gem 'kitchen-vagrant'
gem 'test-kitchen'
gem 'serverspec'
gem 'inspec'