source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef'
gem 'chef-provisioning-aws'
#gem 'chef-provisioning-docker'
gem 'chef-provisioning-vagrant'
gem 'chefspec'
gem 'librarian-chef'
#gem 'docker'
#gem 'docker-api', '~> 1.26', '>= 1.26.2'
#gem 'kitchen-docker'
gem 'kitchen-ec2'
gem 'kitchen-vagrant'
gem 'test-kitchen', '~> 1.4.1'
gem 'serverspec'
gem 'inspec'