name             'my-base'
maintainer       'Richard Whitney'
maintainer_email 'x@gmail.com'
license          'All rights reserved'
description      'Wraps base server settings'
version          '0.1.0'

depends 'apt'
depends 'logrotate'
depends 'ntp'
depends 'openssh'
depends 'ssh_known_hosts'