name             'deploy'
maintainer       'Richard Whitney'
maintainer_email 'x@gmail.com'
license          'All rights reserved'
description      'Installs/Configures demo app stacks'
version          '0.1.0'
