name             'custom_recipes'
maintainer       'Richard Whitney'
maintainer_email 'x@gmail.com'
license          'All rights reserved'
description      'Installs/Configures Existing Recipes'
long_description 'Provides base modifications chef instances'
version          '0.1.0'

depends 'logrotate'
depends 'tomcat'
depends 'java'